### ISSUE TITLE
dosn't work hr_scale hires fix

### ISSUE THREAD

**Issue by TimmekHW** [capslock/stable-diffusion-bot#7] opened 2023-04-26 19:49 UTC
hires fix upscaler doesn't work.
Either you need to fix it, or you need a SendToExtract button

[txt2img]
enable_hr = true
denoising_strength = 2
hr_scale = 2
hr_upscaler = "4x_foolhardy_Remacri"
hr_second_pass_steps = 2

![01211-3804583583](https://user-images.githubusercontent.com/94626112/234686420-7fb6d614-9e47-411a-9f43-06c91ec22439.png)

hires fix works, but there is no upscaling, and denoising_strength is 0. I set it to 0.2 (as expected), but it doesn't help.
and with denoising_strength 0.2 stable-diffusion-bot crashes

dress, black hair, seashore
Negative prompt: easynegative, worst quality, bad-hands-5, bad-artist bad_prompt_version2:0.5, 3 hands, 3 legs
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 5.0, Seed: 3804583583, Size: 512x768, Model hash: 4cf7896571, Model: anime_world_by_Timmek, Seed resize from: -1x-1, Denoising strength: 0

**Comment by capslock** [comment] 2023-04-26 20:39
It seems to work fine for me. Note that if you are using the `db_path` setting, your settings will be saved to the db and will not be overwritten by the new defaults from the config file. You can delete the `db.sqlite` file or comment out the `db_path` from the config file to test out a new configuration without saved settings.

**Comment by capslock** [comment] 2023-05-03 05:47
Closing since I can't reproduce. If you're still experiencing this issue, feel free to re-open.

**Closed by capslock** 2023-05-03 05:47 UTC
