### ISSUE TITLE
tg bot stuck after pressing rerun on old picture

### ISSUE THREAD

**Issue by inqoperated** [capslock/stable-diffusion-bot#26] opened 2023-12-31 07:59 UTC
stable-diffusion-bot[41906]: An error has occurred in the dispatcher: A Telegram's error: Unknown error: "Bad Request: query is too old and response timeout expired or query ID is invalid"

                                                  Caused by:
                                                      Unknown error: "Bad Request: query is too old and response timeout expired or query ID is invalid"

then the bot does not generate images anymore

**Comment by capslock** [comment] 2023-12-31 17:31
This error should generally not happen just when pressing rerun on an old image. It generally indicates that the bot took too long to respond to the button press. The bot will process messages from each user sequentially, so this could mean that the bot was busy waiting for a previous image to finish generating when a new request was made.

I can reproduce this by spamming the rerun button on an image, but the bot continues to work even after generating the error.

Are you able to reproduce this, or was it a one-off error?

**Comment by inqoperated** [comment] 2023-12-31 22:19
maybe coincedence there. i just have noticed the bot is stuck sometimes. i will try to figure it out once i have my new system running

**Comment by capslock** [comment] 2023-12-31 23:15
This may be related to https://github.com/capslock/stable-diffusion-bot/issues/28, as prior to the fix there `comfyui-api` re-used client id's and I observed it getting stuck because of that.

**Comment by capslock** [comment] 2024-01-02 23:52
I'm assuming this is fixed with the fix to https://github.com/capslock/stable-diffusion-bot/issues/28 / https://github.com/capslock/stable-diffusion-bot/commit/97fa2f35cd52f64ecf7c2d5053d7516ce85c6af1. Please re-open if you still see the issue.

**Closed by capslock** 2024-01-02 23:52 UTC
